platform :ios, '13'
use_modular_headers!

target 'FeeRateKitExample' do
  pod 'FeeRateKit.swift', :path => '../'
  pod 'HsToolKit.swift', git: 'https://github.com/baboaisystem/lib_hstool_swift'
end

target 'FeeRateKitTests' do
  pod 'FeeRateKit.swift', :path => '../'
end
